# Generated by Django 5.2.3 on 2025-09-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='paypal_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
