# Generated by Django 5.2.3 on 2025-09-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_payment_amount_alter_payment_paypal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paypal_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
