# Generated by Django 5.2.3 on 2025-09-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_payment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paypal_id',
            new_name='payment_id',
        ),
    ]
