# Generated by Django 5.2.3 on 2025-09-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_paypal_id_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_signature',
            field=models.UUIDField(default='35dd208d-c285-447d-a691-7cc50b19398e'),
            preserve_default=False,
        ),
    ]
