# Generated by Django 5.2.3 on 2025-09-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_payment_items_payment_order_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Complted', 'Completed'), ('Failed', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
