# Generated by Django 5.2.3 on 2025-09-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Complted', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
